language: bash
dist: bionic
before_install:
  - sudo apt-get update
  - sudo apt-get -y install aptitude
  - sudo aptitude -y install nodejs npm openjdk-11-jdk shellcheck
  - sudo npm install -g bats http-server
install: skip
script:
  - bats ./test/test.bats
  - shellcheck -e SC2015 -e SC2016 ./spki
